### ISSUE TITLE
cli和vs启动项目的处理方式不一样吗

### ISSUE THREAD

**Issue by BraveJJJ** [colinin/abp-next-admin#1000]
使用dotnet run启动正常，在vs启动报错。

![8636399051a65a2be3f096850d3e3685](https://github.com/user-attachments/assets/685fb2db-1c0f-49f0-aa77-706e67355661)

![619291d965f1328055326921bf9d9793](https://github.com/user-attachments/assets/19719801-a8e2-47b8-b52f-4b597dd26800)

我想在vs打断点调试发现了这个问题

**Comment by GHxiaohui** [comment]
我手动将localnuget下 LINGYUN.Abp.Logging.Serilog.Elasticsearch删除就好了，但是msbuild和dotnet cli的启动方式还是有区别，这个问题暂时不用处理了

**Comment by colinin** [comment]
VS不能解析不在解决方案文件中引入的其他本地项目，在运行前必须dotnet restore执行一次
