### ISSUE TITLE
elsa3.x已支持多租户

### ISSUE THREAD

**Issue by XuJin186** [colinin/abp-next-admin#1002]
大佬,请意向迁移到elsa3嘛,感谢

**Comment by colinin** [comment]
后面再考虑

**Comment by colinin** [comment]
已查看elsa 3.2.1 发布版本源代码，发现没有提供多租户的支持，首页路线图也没有完成，暂时不考虑集成

**Comment by XuJin186** [comment]
请参考
https://github.com/elsa-workflows/elsa-core/releases/tag/3.3.0-rc1
