### ISSUE TITLE
为TextTemplate添加多租户功能

### ISSUE THREAD

**Issue by Firestorm01** [colinin/abp-next-admin#1003]
因需要为每个租户提供自定义TextTemplate的功能，如果可以的话请添加此功能或者提供一下实现思路。

**Comment by colinin** [comment]
https://github.com/colinin/abp-next-admin/commit/c652ce61e23f8d52857126fe186f0a1603dfc576#diff-6831b05091335ffd0dd128e27ba19b595476ff64048de68ba0cf9cdb873f79a9

**Comment by Firestorm01** [comment]
@colinin 非常感谢，我修改一下试试
