### ISSUE TITLE
【分布式权限管理】当前权限管理的难点

### ISSUE THREAD

**Issue by colinin** [colinin/abp-next-admin#114]
当前权限管理太过于集中，框架依赖于**IPermissionDefinitionProvider**，如果要管理权限，则Admin模块必须依赖于权限配置模块，如果权限越来越多，很难有效的管理（查询权限也会越来越慢）
 
  **解决要点：**

  1、创建一个基础模块，定义接口**IPermissionRegisterContributer**，该接口在应用启动时通过扫描**IPermissionDefinitionProvider**来向权限中心注册项目权限；

  2、**IPermissionRegisterContributer**的实现可以是分布式事件的发布者，权限中心通过订阅此事件向自身的**IPermissionDefinitionProvider**接口注入对应的权限，而后续所有的权限管理都通过权限中心来实现，解耦具体的业务权限与管理模块

  3、待续，应该还有更好的思路；而且SettingManagement、FeatureManagement等都可以采用这种思路

**Comment by seayxu** [comment]
是否可以考虑动态权限管理,不依赖 `IPermissionDefinitionProvider`, 而是通过管理页面来新增修改.

**Comment by colinin** [comment]
> 是否可以考虑动态权限管理,不依赖 `IPermissionDefinitionProvider`, 而是通过管理页面来新增修改.

是可以实现的，其实最佳实践是高度定制Ocelot网关,在路由层面控制权限,内部服务不再暴露接口,所以也就不需要定义权限

**Comment by seayxu** [comment]
这样就必须依赖网关,可以通用化一些.

**Comment by colinin** [comment]
那就是观察者模式了，发布订阅，然后参照框架的审计日志模式，用应用名称来区分不同服务的权限

**Comment by ZhaoYis** [comment]
网关就是网关，只做和网关相关的事情，尽量还是不要囊括譬如权限检查、管理这些，个人觉得还是要到具体服务里面去

**Comment by colinin** [comment]
> 网关就是网关，只做和网关相关的事情，尽量还是不要囊括譬如权限检查、管理这些，个人觉得还是要到具体服务里面去

认证鉴权这部分本来就应该是入口的事情，应用服务只对用户、特征、类型验证感兴趣

**Comment by laosandegudai** [comment]
> > 网关就是网关，只做和网关相关的事情，尽量还是不要囊括譬如权限检查、管理这些，个人觉得还是要到具体服务里面去
> 
> 认证鉴权这部分本来就应该是入口的事情，应用服务只对用户、特征、类型验证感兴趣

是否考虑换个网关，对Ocelot有点信心不足。Kong挺好的，设计不错，第三方客户端或者自己适配问题都不大。

**Comment by colinin** [comment]
> > > 网关就是网关，只做和网关相关的事情，尽量还是不要囊括譬如权限检查、管理这些，个人觉得还是要到具体服务里面去
> > 
> > 
> > 认证鉴权这部分本来就应该是入口的事情，应用服务只对用户、特征、类型验证感兴趣
> 
> 是否考虑换个网关，对Ocelot有点信心不足。Kong挺好的，设计不错，第三方客户端或者自己适配问题都不大。

Kong的可定制性没有Ocelot好（或者说技术栈不同吧），Ocelot可以随时扩展，它的主要性能影响是采用的ASP.NET Core中间件，这是硬伤

**Comment by laosandegudai** [comment]
> > > > 网关就是网关，只做和网关相关的事情，尽量还是不要囊括譬如权限检查、管理这些，个人觉得还是要到具体服务里面去
> > > 
> > > 
> > > 认证鉴权这部分本来就应该是入口的事情，应用服务只对用户、特征、类型验证感兴趣
> > 
> > 
> > 是否考虑换个网关，对Ocelot有点信心不足。Kong挺好的，设计不错，第三方客户端或者自己适配问题都不大。
> 
> Kong的可定制性没有Ocelot好（或者说技术栈不同吧），Ocelot可以随时扩展，它的主要性能影响是采用的ASP.NET Core中间件，这是硬伤
> 
> 不过建议生产环境对于性能要求高的还是用Kong，配上UI之后是很好管理的，我目前就是用的Kong，这个项目只是abp的扩展，所以还是Ocelot

这正是kong的厉害之处，设计优秀语言无关性，良好的api设计方便第三方客户端开发，语言无关性也是微服务里面设计是否良好的标准之一，不然扩展能力、适应兼容行就不够好了。不过使用Ocelot可以快速落地也是比较重要的。

**Comment by laosandegudai** [comment]
> > > > 网关就是网关，只做和网关相关的事情，尽量还是不要囊括譬如权限检查、管理这些，个人觉得还是要到具体服务里面去
> > > 
> > > 
> > > 认证鉴权这部分本来就应该是入口的事情，应用服务只对用户、特征、类型验证感兴趣
> > 
> > 
> > 是否考虑换个网关，对Ocelot有点信心不足。Kong挺好的，设计不错，第三方客户端或者自己适配问题都不大。
> 
> Kong的可定制性没有Ocelot好（或者说技术栈不同吧），Ocelot可以随时扩展，它的主要性能影响是采用的ASP.NET Core中间件，这是硬伤
> 
> 不过建议生产环境对于性能要求高的还是用Kong，配上UI之后是很好管理的，我目前就是用的Kong，这个项目只是abp的扩展，所以还是Ocelot

这正是kong的厉害之处，设计优秀语言无关性，良好的api设计方便第三方客户端开发，语言无关性也是微服务里面设计是否良好的标准之一，不然扩展能力、适应兼容行就不够好了。不过使用Ocelot可以快速落地也是比较重要的。

**Comment by colinin** [comment]
新的灵感，在这里记录一下

过去一直被Abp自带的权限管理模块限制了，我们完全可以实现自己的权限管理模块，把权限信息写进数据库中，并且定义一个名为Application（或者说App）的字段，来限制每个应用程序对于自身的权限检查

定义一个 DatabasePermissionDefinitionProvider（RemoteServicePermissionDefintionProvider），应用程序在启动时加载自身的所有权限定义即可，管理端则能拥有获取所有权限定义的能力

**Comment by laosandegudai** [comment]
> 新的灵感，在这里记录一下
> 
> 过去一直被Abp自带的权限管理模块限制了，我们完全可以实现自己的权限管理模块，把权限信息写进数据库中，并且定义一个名为Application（或者说App）的字段，来限制每个应用程序对于自身的权限检查
> 
> 定义一个 DatabasePermissionDefinitionProvider（RemoteServicePermissionDefintionProvider），应用程序在启动时加载自身的所有权限定义即可，管理端则能拥有获取所有权限定义的能力

主要看你怎么定义权限，权限是对既有内容还是需要对动态内容？

**Comment by colinin** [comment]
> > 新的灵感，在这里记录一下
> > 过去一直被Abp自带的权限管理模块限制了，我们完全可以实现自己的权限管理模块，把权限信息写进数据库中，并且定义一个名为Application（或者说App）的字段，来限制每个应用程序对于自身的权限检查
> > 定义一个 DatabasePermissionDefinitionProvider（RemoteServicePermissionDefintionProvider），应用程序在启动时加载自身的所有权限定义即可，管理端则能拥有获取所有权限定义的能力
> 
> 主要看你怎么定义权限，权限是对既有内容还是需要对动态内容？

不脱离Abp既有的权限系统，只是把PermissionDefinition的信息存储在数据库中

**Comment by colinin** [comment]
可以通过另类的方式来避免管理项目直接引用不同模块的权限定义，比如通过Abp提供的插件系统，把外部权限定义的接口类作为插件部署在管理项目的插件目录，实现启动时加载预置权限

**Comment by zqhgit001** [comment]
老铁，abp-vue是不是你停止更新了

**Comment by zqhgit001** [comment]
老铁，您的邮箱地址是多少？或者QQ是多少？我的QQ：68383913，我可以把详细的错误信息和错误图片发给你，谢谢！
