### ISSUE TITLE
【关于项目更新与问题处理】

### ISSUE THREAD

**Issue by colinin** [colinin/abp-next-admin#183]
最近收到邮件提醒（催更啊小伙子...）问我是不是放弃这个项目，我想abp框架不停更我就不放弃，正式项目正在用某些模块，前端纯属个人学习Vue，所以很多地方大量重复编码，界面也不美观（css从入门到放弃）

  项目不会停止，只是年底了，太太太太太忙了，昨天1点半打的下班卡。。。
 
  等放假了，我就有充足的精力来维护这个项目，和处理问题了，如果现在发现问题，可以开个issue，或者联系我的邮箱，谢谢

**Comment by colinin** [comment]
全力做现有项目，暂时不更新，随abp框架更新

**Comment by zqhgit001** [comment]
老铁，你的ABP-VUE 我折腾了2天还没有运行起来啊，求帮助！

**Comment by XuJin186** [comment]
> 老铁，你的ABP-VUE 我折腾了2天还没有运行起来啊，求帮助！
做个开源项目感觉像是给你全职服务的

**Comment by zqhgit001** [comment]
老铁，您的邮箱地址是多少？或者QQ是多少？我的QQ：68383913，我可以把详细的错误信息和错误图片发给你，谢谢！

**Comment by colinin** [comment]
> > 老铁，你的ABP-VUE 我折腾了2天还没有运行起来啊，求帮助！
> > 做个开源项目感觉像是给你全职服务的

补充一下，我的全职是为目前所在的公司服务，公司业务没有完成，很难分出精力继续维护，只有抽空更新

**Comment by colinin** [comment]
> 老铁，您的邮箱地址是多少？或者QQ是多少？我的QQ：68383913，我可以把详细的错误信息和错误图片发给你，谢谢！

colin.in@foxmail.com
