### ISSUE TITLE
基于 Ant Design Blazor 的 .NET 全栈模板

### ISSUE THREAD

**Issue by ElderJames** [colinin/abp-next-admin#291]
您好，您的这个项目简直叹为观止。

请问会考虑使用Blazor做一套么？这样就能整个项目都使用.NET技术栈了，对.NET团队来说是莫大的帮助，我所了解到的abp社区也有很多对Blazor的呼声。

这个是 Ant Design Pro 主题的静态模板：https://github.com/ant-design-blazor/ant-design-pro-blazor

也有几个demo，但是没有太多的功能：
https://github.com/struggle3/MyAbp
https://github.com/chaldea/ant-design-blazor-abp
https://github.com/TFInfoTech/TF.Abp.Blazor.Layout

有任何问题都可以讨论，感谢您对abp和.NET的贡献！

**Comment by colinin** [comment]
我前端一碗水的水平。。这段时间在做app，我先码一下，抽空学学blazor吧

**Comment by ElderJames** [comment]
哈哈，过于谦虚了。Blazor对于.NET开发者来说是比vue更简单，看看文档就会了。

因为正是给前端知识较少的.NET开发者使用的高效WebUI框架，所以我才来找您做这方面的集成，对.NET开发者来说是非常好的！

**Comment by colinin** [comment]
只要有一个Antd-Blazor的Abp主题，后面的页面就很好搭建

**Comment by ElderJames** [comment]
我上面提供的几个示例应该够了？

**Comment by XuJin186** [comment]
Abp官方还没有把Toolbars抽离出来  假如要完全和Abp体系一样的话  还挺难的   除非自成一体系   我之前尝试过 放弃了

**Comment by colinin** [comment]
> Abp官方还没有把Toolbars抽离出来 假如要完全和Abp体系一样的话 还挺难的 除非自成一体系 我之前尝试过 放弃了

改变主题就行了，Layout自定义，菜单不同之处abp框架提供了扩展属性来适配

**Comment by colinin** [comment]
> 我上面提供的几个示例应该够了？

我到时候看看吧

**Comment by XuJin186** [comment]
行吧  具体的问题具体讨论
