### ISSUE TITLE
【重构预告】5.0版本

### ISSUE THREAD

**Issue by colinin** [colinin/abp-next-admin#325]
将在abp5.0版本后不久发布，解决以下几个问题：

1、配置文件（appsettings.json）全部移动到项目目录；
2、重命名容易引起混淆的项目名称（IdentityServer4、IdentityServer.HttpApi、ApiGateway.Host、ApiGateway.HttpApi）
3、创建直接在windows本机一键部署的docker脚本
4、ApiGate（网关）默认使用ocelot.json文件启动
5、**存储库重命名为：abp-next-admin**
6、移除vueJs
7、建立新的项目目录结构

**Comment by weibinlong** [comment]
用ocelot做网关还是一如既往的痛苦，唉，已经放弃它换APISIX了

**Comment by Jesn** [comment]
请问` abp-next-admin` 大概什么时候出，今天build下`abp-vue-admin-element-typescript`，发现sdk 还是2.0 版本的

**Comment by colinin** [comment]
> 请问` abp-next-admin` 大概什么时候出，今天build下`abp-vue-admin-element-typescript`，发现sdk 还是2.0 版本的，另外文档也比较少，对于初接触者，根本就不知道该怎么把项目跑起来，建议可以组织一个开源小组大家进行分工，一个人搞这么大一个开源是在是太累了

5.0.0-rc.1分支可以拉下来自己看看，建议在新目录下克隆，另外.net standard 2.0并不代表是2.0的sdk，你先弄清楚.net standard、.NET、.NET Core这些名词吧

**Comment by weibinlong** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by colinin** [comment]
提交第一个预发布版本

**Comment by geffzhang** [comment]
5.0 已经发布了

**Comment by colinin** [comment]
> 5.0 已经发布了

已经更新到5.0正式版，仓库已变更名字

**Comment by feijie999** [comment]
cli工具没有更新吧？dotnet tool install --global LINGYUN.Abp.Cli --version 5.0.0

**Comment by colinin** [comment]
windows部署脚本不是特别需要，此issue暂时关闭
