### ISSUE TITLE
工具问题

### ISSUE THREAD

**Issue by dbabox** [colinin/abp-next-admin#452]
参照readme中的文档执行：dotnet tool install --global LINGYUN.Abp.Cli --version 5.0.0
报错：
 error NU1212: LINGYUN.Abp.Cli 5.0.0 的项目包组合无效。DotnetToolReference 项目类型仅可包含 DotnetTool 类型的引用
无法还原工具包。
工具“lingyun.abp.cli”安装失败。此故障可能由以下原因导致:

* 你尝试安装预览版，但未使用 --version 选项来指定该版本。
* 已找到具有此名称的包，但是它不是 .NET 工具。
* 无法访问所需的 NuGet 源，这可能是由于 Internet 连接问题导致。
* 工具名称输入错误。

有关更多原因(包括强制包命名)，请访问 https://aka.ms/failure-installing-tool

**Comment by colinin** [comment]
5.0.1，看nuget版本
