### ISSUE TITLE
全新克隆的项目无法启动，cap模块需要更新

### ISSUE THREAD

**Issue by zsq1576154634** [colinin/abp-next-admin#466]
不然种子数据无法初始化
![image](https://user-images.githubusercontent.com/52565295/149467376-8415cb55-fd02-44d9-a942-5a79eaf45938.png)

**Comment by colinin** [comment]
无法启动？请提供一下启动日志. 我这里并没有什么问题

**Comment by colinin** [comment]
可能是另一个问题的关联
#469
