### ISSUE TITLE
登录时提示未获得授权

### ISSUE THREAD

**Issue by xgd224743** [colinin/abp-next-admin#487]
登录时，
http://localhost:3100/connect/connect/token    200
http://localhost:3100/api/api/abp/application-configuration?_t=1643963038382  200
http://localhost:3100/connect/connect/userinfo?_t=1643963040606  200

http://localhost:3100/api/api/platform/menus/by-current-user?Framework=Vue Vben Admin&_t=1643963040709   401 Unauthorized

请问这是什么原因，如果把相关权限验证拿掉则提示获取不到相关CurrentUserId

**Comment by xgd224743** [comment]
补充，调试状态下，HttpAPI 项目中的Controller，跟踪变量，this.User.Identity.Claims
![1643964637(1)](https://user-images.githubusercontent.com/4489933/152499509-cec4248b-3720-4fcd-bbef-0c723ed64ad1.png)
一切正常

**Comment by xgd224743** [comment]
在方法转到Service中时，则显示CurrentUser为空，没有CurrentUser所以无法获得授权。

**Comment by xgd224743** [comment]
![1643965576(1)](https://user-images.githubusercontent.com/4489933/152501825-48d5d1fb-4002-4612-a484-624b54f4e950.png)
在这里加上去除所有验证，则可以进行方法并且可以获取相关用户数据。

**Comment by xgd224743** [comment]
最后补充，除LY.MicroService.identityServer.HttpApi.Host这个项目，其它项目都无法正常获取到claims

**Comment by xgd224743** [comment]
您好，请在backendadmin项目中添加两个引用
namespace LY.MicroService.BackendAdmin;

[DependsOn(
    typeof(AbpSerilogEnrichersApplicationModule),
    typeof(AbpSerilogEnrichersUniqueIdModule),
    typeof(AbpAspNetCoreSerilogModule),
    typeof(AbpLoggingSerilogElasticsearchModule),
    typeof(AbpAuditLoggingElasticsearchModule),
    typeof(AbpAspNetCoreMvcUiMultiTenancyModule),
    typeof(AbpSettingManagementApplicationModule),

    //必需引用，不然无法获取相关权限列表
      typeof(LINGYUN.Abp.Identity.AbpIdentityApplicationContractsModule),
      typeof(LINGYUN.Abp.IdentityServer.AbpIdentityServerApplicationContractsModule),

**Comment by LuceLuo** [comment]
> 

所有的项目都需要这样加上吗？

**Comment by colinin** [comment]
统一回复，build目录下，执行一次build-aspnetcore-modules.ps1脚本文件，将依赖的模块作为插件引用到backend-admin项目即可
