### ISSUE TITLE
前端合并服务端翻译咨询

### ISSUE THREAD

**Issue by lszai90** [colinin/abp-next-admin#500]
![image](https://user-images.githubusercontent.com/40080599/155165954-768d2c48-9a6e-4ba2-849c-828a52edf86e.png)
合并翻译的时候 后端的翻译
t('AbpAccount.DisplayName:UserName') 这样识别不了。

http://localhost:3100/api/api/abp/application-configuration?_t=1645543806210
返回的结果来看里面的翻译是获取到的：
"AbpAccount": {
        "'{0}' and '{1}' do not match.": "'{0}'与'{1}'不匹配.",
        "The {0} field is not a valid credit card number.": "字段{0}不是有效的信用卡号码.", 
        "DisplayName:UserName": "用户名",
        "DisplayName:Email": "电子邮件",
        "DisplayName:Name": "名字",
        "DisplayName:Surname": "姓",
        "DisplayName:Password": "密码",
      .........
      }
本身前端的翻译是能进行翻译的、只是后端的翻译合并后。在前端用t('') 这样识别不了 大神能否指点一下

**Comment by colinin** [comment]
受限于il18n，无法读取某些格式的json，已经封装了一个可以处理的hooks：
import { useLocalization } from '/@/hooks/abp/useLocalization';
const { L } = useLocalization('AbpAccount');
L('DisplayName:Surname')

**Comment by lszai90** [comment]
受教了。
