### ISSUE TITLE
abp-vnext-pro vs. abp-next-admin

### ISSUE THREAD

**Issue by 12dollar** [colinin/abp-next-admin#507]
I use this post to keep you updated about something I've brought up here: https://github.com/WangJunZzz/abp-vnext-pro/issues/33

I think it could be beneficial if the two projects join forces since both build upon vben and abp.

Google translate:

我用这篇文章让你了解我在这里提出的一些事情：https://github.com/WangJunZzz/abp-vnext-pro/issues/33

我认为如果这两个项目联合起来可能是有益的，因为它们都建立在 vben 和 abp 之上。

**Comment by colinin** [comment]
你所说的项目更适合新手了解abp和vben，至少他的文档很齐全，我这葛主要是内部项目衍生的一些abp扩展模块，可以学习如何为abp框架编写扩展模块，如何重写abp模块等
