### ISSUE TITLE
TaskManagement问题咨询

### ISSUE THREAD

**Issue by lszai90** [colinin/abp-next-admin#509]
在identity-server 下 这个配置
  "IdentityServer": {
    "Clients": {
      "AuthManagement": {
        "ClientId": "auth-management",
        "RootUrl": "http://127.0.0.1:44313/"
      },
      "AuthVueAdmin": {
        "ClientId": "vue-admin-element"
      },
      "AuthApiGateway": {
        "ClientId": "ApigatewayHostClient"
      },
      "InternalService": {
        "ClientId": "internal-service-client"
      }
    }
  }

这个ClientId 
"InternalService": {
        "ClientId": "internal-service-client"
      }
和TaskManagement 下
![image](https://user-images.githubusercontent.com/40080599/156153184-74a5f05e-e5bd-4e0d-8fa4-3a83892f3839.png)

这里不对应 导致 一点击 任务调度器的模块就会弹出。

现在这里改了出现另外一个问题：【用户得到授权，但是访问是被禁止的。】  有好多个模块都是这种 特别是这个部分
![image](https://user-images.githubusercontent.com/40080599/156153693-6d6caacd-9758-4084-8257-649d88ddddc0.png)
大佬 能否指教一下

**Comment by colinin** [comment]
内部服务间调用所需要的客户端标识，需要和IdentityServer项目的IdentityServer:Clients里面的InternalService保持一致

**Comment by colinin** [comment]
还有一个建议，内部服务调用客户端别对外公布，并更改客户端的密钥，设定密钥有效时间，因为一般内部调用客户端需要授权所有权限

**Comment by lszai90** [comment]
> 内部服务间调用所需要的客户端标识，需要和IdentityServer项目的IdentityServer:Clients里面的InternalService保持一致

是的 原来的时候就是不一样导致弹出。

现在是改的了的 只是提示了【用户得到授权，但是访问是被禁止的。】 这个也是Clinet标识造成 还是有其他的原因。大佬

**Comment by colinin** [comment]
> > 内部服务间调用所需要的客户端标识，需要和IdentityServer项目的IdentityServer:Clients里面的InternalService保持一致
> 
> 是的 原来的时候就是不一样导致弹出。
> 
> 现在是改的了的 只是提示了【用户得到授权，但是访问是被禁止的。】 这个也是Clinet标识造成 还是有其他的原因。大佬

在客户端管理界面，给客户端授权即可

**Comment by lszai90** [comment]
感谢 大佬  已经解决了。

这个问题 、原因是有些菜单【AbpPermissionGrants】 未初始化进去导致【用户得到授权，但是访问是被禁止的】。 大佬 这个能否有一个初始 数据的一个脚本呀 我记得之前 【element】那个版本有一个数据库的初始化脚本。

**Comment by colinin** [comment]
与此issues无关的问题单独创建一个issues
