### ISSUE TITLE
角色权限问题

### ISSUE THREAD

**Issue by lszai90** [colinin/abp-next-admin#511]
调用接口：http://localhost:3100/api/api/permission-management/permissions?providerName=R&providerKey=admin

![image](https://user-images.githubusercontent.com/40080599/156694351-1d792bac-2c9a-4496-963d-e729300ca0b9.png)
它始终告诉我 没有实现 IAbpAuthorizationService 这个接口

**Comment by colinin** [comment]
检查当前 authorizationService 实现类型，是否重写过此接口, 这是框架层面的问题

**Comment by lszai90** [comment]
嗯   现在是重载了权限服务里面的方法 跳过检查
