### ISSUE TITLE
Identity.Settings.IdentitySettingNames.User.SmsNewUserRegister

### ISSUE THREAD

**Issue by lszai90** [colinin/abp-next-admin#516]
大佬咨询一下：   
![image](https://user-images.githubusercontent.com/40080599/157020662-4cc61e3d-ccf4-4b85-8143-525c87122f38.png)
 
自定义的这个 IdentitySettingDefinitionProvider   提供者里面、未注入到 SettingDefinitions 这里去。 在
![image](https://user-images.githubusercontent.com/40080599/157021116-293262d9-31c6-431a-850f-dd5fa6a9a10a.png)
加载菜单[设置]的时候  提示未定义

大佬这个问题我已经解决了

我在【BackendAdminHttpApiHostModule】 这个模块下依赖注入了【AbpIdentityDomainSharedModule】 这个模块。【SettingDefinitions】 这里面才拿到值了。
 
另外的化话
我看到在【IdentityServerHttpApiHostModule】 这个模块下他是依赖了【AbpIdentityHttpApiModule】 这个模块按照道理说它应该可以 添加到【SettingDefinitions】里面去的,有点没有明白.望大佬解惑一下。

还想问一个问题： 我们wechat、cloud-aliyun、cloud-tencent 的这些配置： 这个是统一在【设置】模块进行设置、还是需要有单独的模块进行设置，前端没有看到具体的模块。

**Comment by colinin** [comment]
你去看看build\modules.dependencies.json这个文件就知道这些设置都从哪里来的了，外部自定义设置通过实现IReadonlySettingAppService接口即可，最终通过在ocelot聚合路由加入设置端点可以自动聚合到前端设置模块

**Comment by lszai90** [comment]
嗯 感谢已全部出来了
![image](https://user-images.githubusercontent.com/40080599/157211583-4ac4cad3-f36e-4bd3-b658-5695a7853d0f.png)
