### ISSUE TITLE
http://localhost:3100/api/api/platform/menus/by-current-user?Framework=Vue%20Vben%20Admin&_t=1646720271886

### ISSUE THREAD

**Issue by wsx-198611** [colinin/abp-next-admin#517]
登录过程中，用户登录成功，但获取菜单列表http://localhost:3100/api/api/platform/menus/by-current-user?Framework=Vue%20Vben%20Admin&_t=1646720271886时出现

用户名：admin
密码：1q2w3E*

2022-03-08 14:49:18 [WRN] [Volo.Abp.AspNetCore.Mvc.ExceptionHandling.AbpExceptionFilter] [31916] [35] - ---------- RemoteServiceErrorInfo ----------
{
  "code": "Volo.Authorization:010001",
  "message": "授权失败! 提供的策略尚未授予.",
  "details": null,
  "data": {},
  "validationErrors": null
}

**Comment by colinin** [comment]
希望你能领会一下HTTP 401代码的意义，我已经回答了无数个这种问题了

**Comment by wsx-198611** [comment]
查看了以前的issue及其中的解决方案，还是无法解决问题

**Comment by colinin** [comment]
https://github.com/colinin/abp-next-admin/pull/530




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年3月21日(星期一) 下午5:21
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [colinin/abp-next-admin] http://localhost:3100/api/api/platform/menus/by-current-user?Framework=Vue%20Vben%20Admin&amp;_t=1646720271886 (Issue #517)





 
查看了以前的issue及其中的解决方案，还是无法解决问题

**Comment by colinin** [comment]
此类问题属于ASP.NET Core认证授权基础，自己领会，至于这个提交什么意思，相信你学会了能看出来




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年3月21日(星期一) 下午5:21
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [colinin/abp-next-admin] http://localhost:3100/api/api/platform/menus/by-current-user?Framework=Vue%20Vben%20Admin&amp;_t=1646720271886 (Issue #517)





 
查看了以前的issue及其中的解决方案，还是无法解决问题

**Comment by wsx-198611** [comment]
> 此类问题属于ASP.NET Core认证授权基础，自己领会，至于这个提交什么意思，相信你学会了能看出来
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2022年3月21日(星期一) 下午5:21 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; "State ***@***.***&gt;; 主题: Re: [colinin/abp-next-admin] http://localhost:3100/api/api/platform/menus/by-current-user?Framework=Vue%20Vben%20Admin&amp;_t=1646720271886 (Issue #517) 查看了以前的issue及其中的解决方案，还是无法解决问题 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: ***@***.***&gt;

多谢，已解决问题，原理学习理解中。
