### ISSUE TITLE
想咨询一下 如何来进行升级.

### ISSUE THREAD

**Issue by lszai90** [colinin/abp-next-admin#519]
比如我们使用时 我们用的是5.1.1   里面有些模块可能有些不全。就比如Saas. 
如何能快速的让这个模块 迁移到现在固有的5.1.1 上,只能手工移植代码吗 还是有工具支撑

**Comment by colinin** [comment]
你可以切换到saas所在分支，我并没有合并到主分支，没时间

**Comment by lszai90** [comment]
好的 大佬辛苦了
