### ISSUE TITLE
脚手架 Cli 问题咨询

### ISSUE THREAD

**Issue by lszai90** [colinin/abp-next-admin#520]
1、我记得之前有脚手架  建立实体 可以对应的生成  服务规约、 服务、仓储 代码。现在我们【LINGYUN.Abp.Cli】脚手架是否支持。是否可以直接用【Volo.Abp.Cli】 这里来生成。

**Comment by colinin** [comment]
labp工具仅适用于特定模板，不用模板创建项目则使用abp命令

**Comment by lszai90** [comment]
好的  大佬辛苦了
