### ISSUE TITLE
执行yarn build,报错

### ISSUE THREAD

**Issue by tianxin8206** [colinin/abp-next-admin#522]
![image](https://user-images.githubusercontent.com/32237514/158780206-412241f4-50b6-4dca-8cf4-3bfe59969e78.png)

**Comment by colinin** [comment]
先yarn还原包

**Comment by tianxin8206** [comment]
已经还原了

**Comment by colinin** [comment]
https://vvbin.cn/doc-next/other/faq.html#%E4%BE%9D%E8%B5%96%E5%AE%89%E8%A3%85%E9%97%AE%E9%A2%98

**Comment by luchaoshuai** [comment]
好像我跑起来是mysql报错，这个在哪里切换到sql server ?

**Comment by colinin** [comment]
too long time

**Comment by luchaoshuai** [comment]
您好，
感谢您的来信，这是一封自动回复，表示我已经收到了您的邮件并尽快处理。
谢谢，祝您一切顺利！
***@***.*** 谨上

**Comment by luchaoshuai** [comment]
您好，
感谢您的来信，这是一封自动回复，表示我已经收到了您的邮件并尽快处理。
谢谢，祝您一切顺利！
***@***.*** 谨上
