### ISSUE TITLE
关联性基础表单翻译

### ISSUE THREAD

**Issue by lszai90** [colinin/abp-next-admin#577]
1、比如我们单表的 创建人 修改人 等

有2种方式:
第一种 直接持久化到数据库 保存起。 就不用去翻译这个人的Key对应的是什么名字
第二种: 把全部拉出来直接放到表里面 ；然后通过拉出来的数据 进行翻译。
大佬有什么好的办法没

**Comment by colinin** [comment]
为节省空间，都是存储操作用户id的方式，你可以在前端页面watch一下表单数据的用户id字段，然后通过identity的api得到用户信息

**Comment by lszai90** [comment]
好的 理解

**Comment by colinin** [comment]
> 好的 谢谢
> 
> 大佬：在请教一个问题 就是我在客开的微服中： 怎么获取abpusers 里面全部的数据。 我看到几个ICurrentUser 和ICurrentTenant 这个当前用户和租户 这里获取不到。 我们在客开微服中 是否可以利用dapr [sidecar] 来调用其他服务中的服务。

官方提供IdentityUserLookupAppService接口用于检索用户信息
