### ISSUE TITLE
系统运行后，初始化数据有两个admin用户和两个admin角色

### ISSUE THREAD

**Issue by sonce** [colinin/abp-next-admin#683]
你好
今天初始化数据库，执行了build-aspnetcore-ef-update.ps，然后运行了所有的service。
seed初始化数据，有两个admin用户和admin角色。
![image](https://user-images.githubusercontent.com/887972/188260505-391548f7-d0ed-418c-a6d1-c08a78c15e3c.png)
![image](https://user-images.githubusercontent.com/887972/188260512-8fab1ebb-2f5d-4502-a23d-fe849344e330.png)

**Comment by colinin** [comment]
多个模块直接或间接引用了Volo.Abp.Identity.Domain模块，如果同时启动，可能存在这种情况，建议间隔时间启动
