### ISSUE TITLE
wechat configuration

### ISSUE THREAD

**Issue by jasonliao-cb** [colinin/abp-next-admin#762]
in the WeChat setting page, only the WeChat official has the configuration of URL and related properties, in reality, the mini program also has the configuration of notification URL and EncodingKeys properties, would we add it separately? ![image](https://user-images.githubusercontent.com/85977888/210491202-6fbf1137-88a6-4ad7-b107-a71021579306.png)

**Comment by colinin** [comment]
Wechat is only a simple integration, you can get the Settings to make api calls

![image](https://user-images.githubusercontent.com/35512826/210498956-61a32cd4-5ffa-4720-a123-423f50233536.png)
