### ISSUE TITLE
Upgrade abp framework 7.0

### ISSUE THREAD

**Issue by colinin** [colinin/abp-next-admin#764]

**Comment by iswing** [comment]
哈哈来啦7.0

**Comment by colinin** [comment]
**ExternalLocalizationStore** need cache,.
* local cache only copies created in the current application, may not be able to global synchronization,;
* distributed cache solution to this problem but leads to the increase of storage space

**Comment by colinin** [comment]
Matters needing attention
1, switch to **LY.MicroService.BackendAdmin.DbMigrator** project, modify the _appsettings.json_ database connection string, set to start the project and operation in order to perform the migration;
2, switch to **LY.MicroService.LocalizationManagement.DbMigrator** project, modify the _appsettings.json_ database connection string, set to start the project and operation in order to perform the migration;
3, switch to **LY.MicroService.RealtimeMessage.DbMigrator** project, modify the _appsettings.json_ database connection string, set to start the project and operation in order to perform the migration;
4. Table conflicts may occur during migration because the migration program has been changed. Run **_dotnet ef migrations script_** to manually migrate the migrations.
