### ISSUE TITLE
端口问题

### ISSUE THREAD

**Issue by lszai90** [colinin/abp-next-admin#778]
1、auth-server     "applicationUrl": "http://127.0.0.1:44385;https://127.0.0.1:44386"
2、identity-server  "applicationUrl": "http://127.0.0.1:44385;https://127.0.0.1:44386",

这个2个服务的端口是否是重复了。

**Comment by colinin** [comment]
identitu-server和auth-server只能使用其中一个（包括各自的api宿主），因为auth使用openiddict作为身份认证提供者，identity-server使用IdentityServer4

**Comment by lszai90** [comment]
嗯嗯 已知晓 已经跑起来了。对了大佬：【LINGYUN.Abp.MicroService.Templates】这个模板的代码能否共享一份

**Comment by colinin** [comment]
下个版本开放源代码，或者邮箱/群联系

**Comment by lszai90** [comment]
我通过 【LINGYUN.Abp.MicroService.Templates】安装的模板通过LINGYUN创建一个模板项目 然后通过【.NET Core自定义项目模板】配置了简单的模板,暂时替换解决方案的名字、但是还没有达到大佬的水平,里面的文件的名字没有被替换掉、.Json对应的参数也没替换、想跟大佬学习一下。邮箱：ls_zai@163.com

**Comment by colinin** [comment]
模板需要两个参数才能全部替换，-pk定义为包名（类似java的设计）

**Comment by colinin** [comment]
PackageName.CompanyName.ProjectName

**Comment by lszai90** [comment]
嗯 这个明白的哇，我用LINGYUN创建好一个项目、用这个项目来作为我的模板，通过【.NET Core自定义项目模板】配置。进行配置、然后安装模板。暂时只做到了作者和名称的替换。 所以上面才向大佬说源码的事情。
![image](https://user-images.githubusercontent.com/40080599/220028461-f8d550b6-e52e-4a70-975a-62a0a3906134.png)

**Comment by colinin** [comment]
就是简单的字符串替换，市面上的模板都是这么做，部分高级点的用到了模板引擎，但是底层一样是字符串替换

**Comment by lszai90** [comment]
好的

**Comment by lszai90** [comment]
对了大佬本次是不能发模板的源码的哈。

**Comment by colinin** [comment]
不开放是因为用到了一个内部业务模块，脱离出来就可以开放了
&nbsp;


Colin
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年2月20日(星期一) 下午3:02
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [colinin/abp-next-admin] 端口问题 (Issue #778)





 
对了大佬本次是不能发模板的源码的哈。

**Comment by lszai90** [comment]
收到




| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | yx ***@***.***> |
| 日期 | 2023年02月20日 15:03 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [colinin/abp-next-admin] 端口问题 (Issue #778) |

不开放是因为用到了一个内部业务模块，脱离出来就可以开放了
&nbsp;


Colin
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;;
发送时间: 2023年2月20日(星期一) 下午3:02
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;; ***@***.***&gt;;
主题: Re: [colinin/abp-next-admin] 端口问题 (Issue #778)






对了大佬本次是不能发模板的源码的哈。
