### ISSUE TITLE
语言新增、修改有点问题

### ISSUE THREAD

**Issue by lszai90** [colinin/abp-next-admin#780]
1、新增的时候未即时刷新网格
2、修改的时候路由错误了：
修改路由后可以执行修改：
export const GetAsyncByName = (name: string) => {
  return defAbpHttp.request<Language>({
    service: remoteServiceName,
    controller: controllerName,
    action: 'GetByNameAsync',
    uniqueName: 'GetByNameAsyncByName',
    params: {
      name: name,
    },
  });
};

**Comment by colinin** [comment]
未全面接管 i18n 组件，添加语言/编辑语言文本后都需要手动刷新
