### ISSUE TITLE
ClientId 问题

### ISSUE THREAD

**Issue by lszai90** [colinin/abp-next-admin#781]
1、 MicroService.IdentityServer 在这里
  "IdentityServer": {
    "Clients": {
      "AuthManagement": {
        "ClientId": "auth-management",
        "RootUrl": "http://127.0.0.1:44313/"
      },
      "AuthVueAdmin": {
        "ClientId": "vue-admin-client"
      },
      "AuthOldVueAdmin": {
        "ClientId": "vue-admin-element"
      },
      "InternalService": {
        "ClientId": "InternalServiceClient"
      }
    }
  },
2、 MicroService.PlatformManagement.HttpApi.Host

  "IdentityClients": {
    "InternalServiceClient": {
      "Authority": "http://127.0.0.1:44385/",
      "RequireHttps": false,
      "GrantType": "client_credentials",
      "Scope": "jgsoft-abp-application",
      "ClientId": "internal-service-client",
      "ClientSecret": "1q2w3e*"
    }
  },

这个2个的ClientId 是否会存在问题

**Comment by colinin** [comment]
真正的ClientId是**_internal-service-client_**，InternalServiceClient这个只是配置项名称，某些环境中配置项不允许出现横线
