### ISSUE TITLE
项目里面配置数据库连接字符串，数据库名有的带后缀-v70，有的不带，是有特殊用意吗

### ISSUE THREAD

**Issue by GHxiaohui** [colinin/abp-next-admin#826]
项目里面配置数据库连接字符串，数据库名有的带后缀-v70，有的不带，是有特殊用意吗

**Comment by colinin** [comment]
abp 7.0版本增加了部分表结构，EF迁移代码重新定义了一下，为防止和老版本混淆

**Comment by GHxiaohui** [comment]
谢谢，我把v70都去掉了，才能跑通，因为启动项目时总会提示说找不到数据库，要是有表单设计和代码生成器就完美了
