### ISSUE TITLE
找不到 LINGYUN.Abp.* Nuget 包

### ISSUE THREAD

**Issue by CacoCode** [colinin/abp-next-admin#838]
![image](https://github.com/colinin/abp-next-admin/assets/97924970/e08277b8-d8a9-4b73-a3ab-993351bf5f02)

**Comment by CacoCode** [comment]
![image](https://github.com/colinin/abp-next-admin/assets/97924970/bba1b610-3751-4ce4-90a4-89ea7de3f2d1)

**Comment by CacoCode** [comment]
可以修改 LINGYUNAbpPackageVersion 属性 为 6.0.2.1。但建议完善生成逻辑或Nuget对应Abp版本

**Comment by colinin** [comment]
nuget包本人不发布，建议clone源代码后，发布到本地nuget服务器，例如Nexus
