### ISSUE TITLE
执行数据库更新报错

### ISSUE THREAD

**Issue by seamusic** [colinin/abp-next-admin#917]
Current Tenant Id is not available!

![image](https://github.com/colinin/abp-next-admin/assets/172009/1e5ffb7d-4cb1-44c4-a50d-2a250fe306a9)

![image](https://github.com/colinin/abp-next-admin/assets/172009/20e8ef5f-7742-41c6-ad06-d2e49c4a166d)

这行注释有问题，删除了就好了

**Comment by colinin** [comment]
在 #919 中已修复
