### ISSUE TITLE
dotnet run error

### ISSUE THREAD

**Issue by mikey5656** [colinin/abp-next-admin#921]
hello author, I encounter some mistakes,
I can't run，not found package in the nuget!
The project running need package version more than nuget provide version .
![image](https://github.com/colinin/abp-next-admin/assets/142763736/1f58d052-e424-4f4f-8637-656ba351c7f4)

**Comment by colinin** [comment]
Because there is no release nuget, so need you to solve the nuget references, can build the project (from **LINGYUN.MicroService.All.sln**) detected, and then released to the local nuget server or file path
