### ISSUE TITLE
部署至K8s，内存占用过高 持续增加占用，PUT、DELETE请求报错

### ISSUE THREAD

**Issue by zhang8043** [colinin/abp-next-admin#931]
目前学习使用将项目部署到k8s,遇到两个问题，
1：内存爆表，项目刚启动admin项目占用约1Gb内存，其他项目平均700Mb左右，内存随着时间还在持续扩增
2：PUT、DELETE请求前端显示400 Bad Request，Swagger调试 204 No Content，导致前端请求报错 
![image](https://github.com/colinin/abp-next-admin/assets/31415437/ca95f6c6-5d1d-49d0-9a63-a49a19471435)
![image](https://github.com/colinin/abp-next-admin/assets/31415437/ce0680e9-342b-4a71-b2cb-7b83863d1667)

**Comment by colinin** [comment]
admin项目涉及到很多动态数据，你可以在本地追踪一下内存引用看看，你这种情况大概率是数据库连接池的问题，你追踪一下日志呢
