### ISSUE TITLE
AbpUINavigationVueVbenAdminNavigationDefinitionProvider.cs 迁移版本比较抛错

### ISSUE THREAD

**Issue by manniuyemanniu** [colinin/abp-next-admin#968]
![image](https://github.com/colinin/abp-next-admin/assets/28796629/5e2e0bd6-87ae-4c25-9dfd-34fe0e4ea09d)

1、 AbpUINavigationVueVbenAdminNavigationDefinitionProvider  217行修正
var versionAttr = assembly.GetCustomAttribute<AssemblyInformationalVersionAttribute>();
 if (versionAttr != null)
 {
     var version = new Version(assembly.GetFileVersion());
     var version6 = new Version("6.0.0");
     removedIdsVersion = version6 >= version;
 }

**Comment by colinin** [comment]
我认为这里可以并行运行，不区分IdentityServer或者OpenIddict

**Comment by manniuyemanniu** [comment]
是我的new version 抛错，不知道是不是.netcore版本不兼容吗?
